In [2]:
import numpy as np
import torch

# 뷰
원소수를 유지하면서 텐서의 크기를 변경한다.  
매우 중요한 기능이므로 꼭 알고 가자  

</br>

파이토치의 뷰는 넘파이의 리쉐이프와 같은 역할을 한다.  
실습을 위해 텐서를 만들자.

In [3]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [4]:
print(ft.shape)

torch.Size([2, 2, 3])


위 텐서 크기는 (2, 2, 3) 이다.

## 3차원 텐서에서 2차원 텐서로 변경
이제 view를 사용해 크기를 2차원으로 바꾸자

In [5]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


처음 3차원 일때와 달리 대괄호 수가 달라진 것을 볼 수 있다.  
view([-1, 3])이 가지는 의미가 뭘까?  
-1은 첫번째 차원은 잘 모르겠으니 토치보고 알아서 하라는 것이고  
3은 두번째 차원의 길이는 3을 가지도록 하라는 의미이다.  
즉, 3차원 텐서를 2차원 텐서로 변경하되 (?, 3)의 크기로  
변경하라는 의미이다.  
결과적으로 (4, 3)의 크기가 된다.  


## 스퀴즈 - 1인 차원을 제거
스퀴즈는 차원이 1인 경우, 해당 차원을 제거한다.

In [6]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


이 텐서는 3 X 1의 크기를 가진다.  
두 번째 차원이 1이므로 스퀴지를 사용하면 (3,) 크기를 가지는 텐서로 변경된다.  


In [7]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


본래 3, 1 크기였지만 두 번째 차원이 제거되면서 (3,) 크기를 가지는 텐서가 되었다.  

## 언스퀴즈 - 특정 위치에 1인 차원을 추가

언스퀴지는 스퀴즈와 정반대이다.  
특정 위치에 1인 차원을 추가한다.  

In [8]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


당장은 차원이 1개인 벡터다.

In [9]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


(3,) 크기를 가졌던 백터가 (1,3)의 2차원 텐서로 변경되었다.  
view로도 구현이 가능하다.  
2차원으로 바꾸고 싶으면서 첫번째 차원이 1이기 바란다면  
view에서 (1, -1)을 인자로 사용하면 된다.

In [10]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


위 결과는 view와 unsqueeze가 동일한 결과를 내놓는 것을 보여준다.  
이번에는 unsqueeze 인자에 1과 -1을 넣어보자

In [11]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


결과가 동일하다.  
맨 뒤에 1인 차원이 추가되면서 1차원 벡터가 (3, 1)의 크기를 가지는 2차원 텐서로 변경되었다.  

## 타입 캐스팅
텐서에는 자료형이 있다.  
예를 들어  
32비트 부동소숫점은 torch.FloatTensor  
64비트 부호정수는 torch.LongTensor를 사용한다.
GPU연산을 위한 자료형으로는 torch.cuda.FloatTensor가 있다.  

</br>

그리고 이 자료형을 변환하는 것을 타입 캐스팅이라고 한다.  
실습을 위해 long타입의 텐서를 사용해보자

In [12]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


텐서에다가 float를 붙이면 바로 float형으로 변한다.

In [13]:
print(lt.float())

tensor([1., 2., 3., 4.])


이번엔 byte 타입의 텐서를 long이나 float로 바꿔보자

In [14]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## 연결하기

이번에는 두 텐서를 연결해보자 (2 x 2)크기의 텐서로 실습해보자  
연결은 .cat()메서드로 실행한다.

In [15]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [16]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


두 텐서를 연결할 때, 어떤 차원을 늘릴 것인지 정해야한다.  
그것이 바로 dim=0이며 이는 첫번째 차원을 늘리라는 의미이다.  
이번엔 dim=1을 줘보자

In [17]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


이번엔 가로로 길어진 것을 볼 수 있다.

## 스택킹
연결을 하는 또 다른 방법이다.  
아래 예시를 통해 확인하자  
예시에서는 x, y, z 라는 3개의 벡터가 있다.

In [18]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

이걸 모두 스택킹해보자

In [19]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


결과적으로 3개의 벡터가 순차적으로 쌓여, 3 X 2 텐서가 되었다.  
이번엔 가로로 쌓아보자

In [20]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


첫 번째와는 다르게, 스택이 가로로 쌓인 것을 알 수 있다.

## 0으로 채워진 텐서와 1로 채워진 텐서
(2 X 3) 텐서를 만들고 그것과 같은 크기의 내부값이 1인  
텐서를 만들어보자

In [21]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [22]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


크기는 동일하면서 내부 값이 1로 되어 있는 텐서 생성  
위 텐서에 zeros_like를 하면 동일한 크기의  
0으로만 채워진 텐서가 만들어 진다.

In [23]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 덮어쓰기 연산
이번엔 2 X 2 텐서를 만들고 곱셈을 한 값과 기존 값을 출력해보자  

In [24]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


첫 번째 출력은 2를 곱한 것을, 두 번째 출력은 기존 값을 나타낸다.  
그런데 연산 뒤에 _를 붙이면 기존값에 덮어쓰기가 된다.  


In [25]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
