In [2]:
import numpy as np
import torch

# 뷰
원소수를 유지하면서 텐서의 크기를 변경한다.  
매우 중요한 기능이므로 꼭 알고 가자  

</br>

파이토치의 뷰는 넘파이의 리쉐이프와 같은 역할을 한다.  
실습을 위해 텐서를 만들자.

In [3]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [4]:
print(ft.shape)

torch.Size([2, 2, 3])


위 텐서 크기는 (2, 2, 3) 이다.

## 3차원 텐서에서 2차원 텐서로 변경
이제 view를 사용해 크기를 2차원으로 바꾸자

In [5]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


처음 3차원 일때와 달리 대괄호 수가 달라진 것을 볼 수 있다.  
view([-1, 3])이 가지는 의미가 뭘까?  
-1은 첫번째 차원은 잘 모르겠으니 토치보고 알아서 하라는 것이고  
3은 두번째 차원의 길이는 3을 가지도록 하라는 의미이다.  
즉, 3차원 텐서를 2차원 텐서로 변경하되 (?, 3)의 크기로  
변경하라는 의미이다.  
결과적으로 (4, 3)의 크기가 된다.  


## 스퀴즈 - 1인 차원을 제거
스퀴즈는 차원이 1인 경우, 해당 차원을 제거한다.

In [6]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


이 텐서는 3 X 1의 크기를 가진다.  
두 번째 차원이 1이므로 스퀴지를 사용하면 (3,) 크기를 가지는 텐서로 변경된다.  


In [7]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


본래 3, 1 크기였지만 두 번째 차원이 제거되면서 (3,) 크기를 가지는 텐서가 되었다.  

## 언스퀴즈 - 특정 위치에 1인 차원을 추가

언스퀴지는 스퀴즈와 정반대이다.  
특정 위치에 1인 차원을 추가한다.  

In [8]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


당장은 차원이 1개인 벡터다.

In [9]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])
